language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

cache:
    directories:
    - vendor/

matrix:
    allow_failures:
    - nightly
    - hhvm
    - hhvm-nightly

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - composer self-update -n
    - composer install --dev -n
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
    - pecl install runkit || true
    - phpenv config-add tests/php.ini

script:
    - vendor/bin/phpunit --coverage-clover clover.xml --bootstrap ./tests/bootstrap.php tests/

after_script:
    - composer require --dev "satooshi/php-coveralls dev-master"
    - php vendor/bin/coveralls -n -v

