language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
    -   hhvm
    -   hhvm-nightly

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then prefer_source="--prefer-source"; else prefer_source=""; fi
    - composer self-update -n
    - composer install --dev -n $prefer_source

script:
    - php -d hhvm.libxml.ext_entity_whitelist=file vendor/bin/phpunit --coverage-clover clover.xml --test-suffix=.php --bootstrap ./tests/bootstrap.php tests/

after_script:
    - composer require --dev $prefer_source "satooshi/php-coveralls dev-master"
    - php vendor/bin/coveralls -n -v

